# Generated by Django 4.2.1 on 2023-05-15 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_name', models.CharField(db_index=True, max_length=100, verbose_name='Назва категорії')),
                ('slug_for_categories', models.SlugField(max_length=255, unique=True, verbose_name='Слаг для категорії')),
            ],
            options={
                'verbose_name': 'Категорія товару',
                'verbose_name_plural': 'Категорії товарів',
                'ordering': ['categories_name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug_for_position', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/', verbose_name='Фото')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Ціна')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата останніх змін')),
                ('published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('in_box', models.BooleanField(default=False, verbose_name='В корзині')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_app1.categories', verbose_name='Категорія в позиціях')),
            ],
            options={
                'verbose_name': 'Товарна одиниця',
                'verbose_name_plural': 'Товарні одиниці',
                'ordering': ['-time_update', 'title'],
            },
        ),
    ]
